/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.mikeneck.ktfmt

import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.api.tasks.SourceSetContainer

/**
 * A simple 'hello world' plugin.
 */
class GradleKtfmtPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        project.tasks.register("ktfmt", KtFmtTask::class.java) {
            it.source(project.fileTree("src/main/kotlin"))
            it.source(project.fileTree("src/test/kotlin"))
        }
    }
}
